name: AC record schedule

on:
  schedule:
    # 0时区每小时的50分启动
    - cron: '50 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Shanghai # 时区

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'yarn'
      - run: yarn install
      - run: |
          git pull
          yarn run ac_record

      - name: Update GitHub
        run: |
          git config --local user.email "1176989591@qq.com"
          git config --local user.name "Anonymity94"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit -m "update by github action"
          git push
